# Generated by Django 4.0.5 on 2022-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20200729_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(null=True, upload_to='noteimages'),
        ),
    ]
